// CARDIO EXERCISES (30+)
export const CARDIO_EXERCISES = [
    { id: 'running-steady', name: 'Course à Pied (Steady State)', targetMuscles: ['quad-rectus', 'calves'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Rythme constant, respirez régulièrement'] },
    { id: 'running-sprints', name: 'Sprints', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'cardio', instructions: ['100% effort sur 20-30 secondes, repos complet'] },
    { id: 'hiit-treadmill', name: 'HIIT Tapis de Course', targetMuscles: ['quad-rectus'], equipment: ['machine'], difficulty: 'intermediate', category: 'cardio', instructions: ['Alternez sprint 30s / marche 60s'] },
    { id: 'cycling-steady', name: 'Vélo Steady State', targetMuscles: ['quad-rectus'], equipment: ['machine'], difficulty: 'beginner', category: 'cardio', instructions: ['Pédalez à cadence constante'] },
    { id: 'cycling-hiit', name: 'Vélo HIIT', targetMuscles: ['quad-rectus'], equipment: ['machine'], difficulty: 'intermediate', category: 'cardio', instructions: ['30s max effort, 30s repos'] },
    { id: 'rowing-machine', name: 'Rameur', targetMuscles: ['lats', 'quad-rectus'], equipment: ['machine'], difficulty: 'intermediate', category: 'cardio', instructions: ['Poussez avec les jambes, tirez avec le dos'] },
    { id: 'elliptical', name: 'Elliptique', targetMuscles: ['quad-rectus'], equipment: ['machine'], difficulty: 'beginner', category: 'cardio', instructions: ['Mouvement fluide, bras actifs'] },
    { id: 'stair-climber', name: 'Stair Master', targetMuscles: ['glutes-max', 'calves'], equipment: ['machine'], difficulty: 'intermediate', category: 'cardio', instructions: ['Montez les marches régulièrement'] },
    { id: 'jump-rope', name: 'Corde à Sauter', targetMuscles: ['calves'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Sautillez légèrement, poignets actifs'] },
    { id: 'double-unders', name: 'Double Unders', targetMuscles: ['calves'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'cardio', instructions: ['La corde passe 2x par saut'] },
    { id: 'burpees', name: 'Burpees', targetMuscles: ['chest-mid', 'quad-rectus'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'cardio', instructions: ['Squat, planche, pompe, saut'] },
    { id: 'box-jumps', name: 'Box Jumps', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'cardio', instructions: ['Sautez sur la box, descendez'] },
    { id: 'squat-jumps', name: 'Jump Squats', targetMuscles: ['quad-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Squat puis sautez explosivement'] },
    { id: 'lunge-jumps', name: 'Jumping Lunges', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'cardio', instructions: ['Fentes avec alternance en saut'] },
    { id: 'high-knees', name: 'High Knees', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Course sur place, genoux hauts'] },
    { id: 'butt-kicks', name: 'Butt Kicks', targetMuscles: ['hamstrings'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Course sur place, talons aux fesses'] },
    { id: 'jumping-jacks', name: 'Jumping Jacks', targetMuscles: ['delt-side'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Sautez, écartez bras et jambes'] },
    { id: 'battle-ropes', name: 'Battle Ropes', targetMuscles: ['delt-front', 'abs-rectus'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'cardio', instructions: ['Ondulez les cordes de toutes vos forces'] },
    { id: 'sled-push', name: 'Prowler Push', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['machine'], difficulty: 'intermediate', category: 'cardio', instructions: ['Poussez le traîneau sur distance'] },
    { id: 'sled-pull', name: 'Sled Pull', targetMuscles: ['lats'], equipment: ['machine'], difficulty: 'intermediate', category: 'cardio', instructions: ['Tirez le traîneau vers vous'] },
    { id: 'assault-bike', name: 'Assault Bike', targetMuscles: ['quad-rectus'], equipment: ['machine'], difficulty: 'advanced', category: 'cardio', instructions: ['Le plus brutal des cardios'] },
    { id: 'swimming', name: 'Natation', targetMuscles: ['lats', 'delt-front'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'cardio', instructions: ['Crawl, brasse ou papillon'] },
    { id: 'hiking', name: 'Randonnée', targetMuscles: ['quad-rectus', 'calves'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Marchez en pente avec intensité'] },
    { id: 'stair-walking', name: 'Montée d Escaliers', targetMuscles: ['glutes-max'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Montez des escaliers à répétition'] },
    { id: 'incline-walk', name: 'Marche Inclinée Tapis', targetMuscles: ['glutes-max', 'calves'], equipment: ['machine'], difficulty: 'beginner', category: 'cardio', instructions: ['Tapis en pente 10-15%, marche rapide'] },
    { id: 'kettlebell-swings', name: 'Kettlebell Swings', targetMuscles: ['glutes-max', 'hamstrings'], equipment: ['kettlebell'], difficulty: 'intermediate', category: 'cardio', instructions: ['Balancez entre les jambes, poussez les hanches'] },
    { id: 'man-makers', name: 'Man Makers', targetMuscles: ['chest-mid', 'quad-rectus'], equipment: ['dumbbell'], difficulty: 'advanced', category: 'cardio', instructions: ['Burpee + Row + Press'] },
    { id: 'thrusters', name: 'Thrusters', targetMuscles: ['quad-rectus', 'delt-front'], equipment: ['barbell'], difficulty: 'intermediate', category: 'cardio', instructions: ['Front squat + push press enchaîné'] },
];

// STRETCHING/MOBILITY EXERCISES (30+)
export const STRETCHING_EXERCISES = [
    { id: 'pec-door-stretch', name: 'Étirement Pecs Cadre de Porte', targetMuscles: ['chest-mid'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Avant-bras contre le cadre, avancez'] },
    { id: 'lat-hang', name: 'Suspension Passive', targetMuscles: ['lats'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Pendez à une barre, laissez-vous étirer'] },
    { id: 'cat-cow', name: 'Cat-Cow', targetMuscles: ['back'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['À quatre pattes, alternez dos rond/creusé'] },
    { id: 'child-pose', name: 'Posture de l Enfant', targetMuscles: ['lats', 'back'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Genoux au sol, bras tendus devant'] },
    { id: 'cobra-stretch', name: 'Cobra', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Allongé, poussez sur les mains, cambrez'] },
    { id: 'hip-flexor-stretch', name: 'Étirement Fléchisseurs de Hanche', targetMuscles: ['quad-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Fente au sol, poussez la hanche avant'] },
    { id: 'pigeon-pose', name: 'Posture du Pigeon', targetMuscles: ['glutes-max'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'stretching', instructions: ['Jambe avant pliée, jambe arr tendue'] },
    { id: 'hamstring-stretch-floor', name: 'Étirement Ischio au Sol', targetMuscles: ['hamstrings'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Jambe tendue, penchez-vous vers le pied'] },
    { id: 'quad-stretch-standing', name: 'Étirement Quad Debout', targetMuscles: ['quad-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Pied au fessier, poussez la hanche'] },
    { id: 'calf-stretch', name: 'Étirement Mollets Mur', targetMuscles: ['calves'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Pied arrière plat, penchez vers le mur'] },
    { id: 'shoulder-pass-through', name: 'Pass Through Bâton', targetMuscles: ['delt-front', 'delt-rear'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Bâton large passe devant/derrière'] },
    { id: 'tricep-stretch', name: 'Étirement Triceps', targetMuscles: ['triceps-long'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Coude derrière la tête, tirez'] },
    { id: 'bicep-doorway-stretch', name: 'Étirement Biceps Cadre', targetMuscles: ['biceps-short'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Main au cadre, tournez le corps'] },
    { id: 'neck-stretch', name: 'Étirement Nuque', targetMuscles: ['traps-upper'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Penchez la tête, tirez doucement'] },
    { id: 'wrist-stretch', name: 'Étirement Poignets', targetMuscles: ['forearms'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Main vers le bas, tirez les doigts'] },
    { id: 'foam-roll-upper-back', name: 'Foam Roll Haut du Dos', targetMuscles: ['traps-mid-lower'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Roulez sur le haut du dos'] },
    { id: 'foam-roll-lats', name: 'Foam Roll Dorsaux', targetMuscles: ['lats'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Sur le côté, roulez les lats'] },
    { id: 'foam-roll-quads', name: 'Foam Roll Quads', targetMuscles: ['quad-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Face au sol, roulez les cuisses'] },
    { id: 'foam-roll-glutes', name: 'Foam Roll Fessiers', targetMuscles: ['glutes-max'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Assis sur le rouleau, roulez'] },
    { id: 'foam-roll-hamstrings', name: 'Foam Roll Ischio', targetMuscles: ['hamstrings'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Jambe sur le rouleau, roulez'] },
    { id: 'foam-roll-calves', name: 'Foam Roll Mollets', targetMuscles: ['calves'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Mollet sur le rouleau'] },
    { id: 'deep-squat-hold', name: 'Deep Squat Hold', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Descendez en squat profond, maintenez'] },
    { id: '90-90-stretch', name: '90-90 Hip Stretch', targetMuscles: ['glutes-max'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'stretching', instructions: ['Les deux jambes à 90°'] },
    { id: 'thoracic-rotation', name: 'Rotation Thoracique', targetMuscles: ['back'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['À genoux, main derrière la tête, tournez'] },
    { id: 'scorpion-stretch', name: 'Scorpion Stretch', targetMuscles: ['abs-rectus', 'quad-rectus'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'stretching', instructions: ['Allongé, croisez le pied vers la main opposée'] },
    { id: 'world-greatest-stretch', name: 'World s Greatest Stretch', targetMuscles: ['quad-rectus', 'back'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'stretching', instructions: ['Fente, rotation thoracique, jambe tendue'] },
    { id: 'ankle-mobilization', name: 'Mobilisation Cheville', targetMuscles: ['calves'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Genou vers l avant, talon au sol'] },
    { id: 'supine-twist', name: 'Torsion Allongée', targetMuscles: ['back', 'obliques'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'stretching', instructions: ['Genoux d un côté, épaules au sol'] },
];

// FUNCTIONAL/COMPOUND EXERCISES (20+)
export const FUNCTIONAL_EXERCISES = [
    { id: 'clean', name: 'Clean (Épaulé)', targetMuscles: ['quad-rectus', 'traps-upper'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Tirez la barre du sol aux épaules en un mouvement explosif'] },
    { id: 'snatch', name: 'Arraché (Snatch)', targetMuscles: ['delt-front', 'quad-rectus'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Barre du sol au-dessus de la tête'] },
    { id: 'clean-and-jerk', name: 'Épaulé-Jeté', targetMuscles: ['quad-rectus', 'delt-front'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Épaulé puis poussez au-dessus'] },
    { id: 'power-clean', name: 'Power Clean', targetMuscles: ['quad-rectus', 'traps-upper'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Épaulé sans descendre en squat'] },
    { id: 'hang-clean', name: 'Hang Clean', targetMuscles: ['traps-upper'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Départ mi-cuisse'] },
    { id: 'db-snatch', name: 'DB Snatch', targetMuscles: ['delt-front'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Un bras, sol au-dessus'] },
    { id: 'kb-snatch', name: 'KB Snatch', targetMuscles: ['delt-front'], equipment: ['kettlebell'], difficulty: 'intermediate', category: 'strength', instructions: ['Kettlebell du sol au-dessus'] },
    { id: 'turkish-getup', name: 'Turkish Get Up', targetMuscles: ['abs-rectus', 'delt-front'], equipment: ['kettlebell'], difficulty: 'advanced', category: 'strength', instructions: ['Du sol debout avec poids au-dessus'] },
    { id: 'kb-clean-press', name: 'KB Clean and Press', targetMuscles: ['delt-front'], equipment: ['kettlebell'], difficulty: 'intermediate', category: 'strength', instructions: ['Épaulé puis press'] },
    { id: 'wall-balls', name: 'Wall Balls', targetMuscles: ['quad-rectus', 'delt-front'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'cardio', instructions: ['Squat, lancez le medball au mur'] },
    { id: 'medball-slams', name: 'Med Ball Slams', targetMuscles: ['abs-rectus', 'lats'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Levez le ballon, smashlez au sol'] },
    { id: 'medball-rotational-throw', name: 'Lancé Rotationnel', targetMuscles: ['obliques'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Rotation du buste, lancez sur mur'] },
    { id: 'tire-flip', name: 'Tire Flip', targetMuscles: ['back', 'quad-rectus'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Soulevez et retournez le pneu'] },
    { id: 'yoke-walk', name: 'Yoke Walk', targetMuscles: ['traps-upper', 'abs-rectus'], equipment: ['machine'], difficulty: 'advanced', category: 'strength', instructions: ['Marchez avec le joug sur les épaules'] },
    { id: 'atlas-stones', name: 'Atlas Stones', targetMuscles: ['back', 'biceps-short'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Soulevez la pierre sur la plateforme'] },
    { id: 'log-press', name: 'Log Press', targetMuscles: ['delt-front'], equipment: ['machine'], difficulty: 'advanced', category: 'strength', instructions: ['Press avec le log de strongman'] },
    { id: 'sandbag-carry', name: 'Sandbag Carry', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Portez le sac sur distance'] },
    { id: 'suitcase-carry', name: 'Suitcase Carry', targetMuscles: ['obliques'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Haltère d un côté, marchez droit'] },
    { id: 'overhead-carry', name: 'Overhead Carry', targetMuscles: ['delt-front', 'abs-rectus'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Poids au-dessus, marchez'] },
    { id: 'zercher-carry', name: 'Zercher Carry', targetMuscles: ['biceps-short', 'abs-rectus'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Barre dans le creux des coudes, marchez'] },
];
