import type { Exercise, Equipment, Difficulty, ExerciseCategory } from './exercise-types';

// CHEST EXERCISES (50+)
export const CHEST_EXERCISES: Exercise[] = [
    { id: 'flat-bb-press', name: 'Développé Couché Barre', targetMuscles: ['chest-mid'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Position allongée, pieds au sol, saisissez la barre', 'Descendez contrôlé au sternum', 'Poussez vers le haut'] },
    { id: 'incline-bb-press', name: 'Développé Incliné Barre', targetMuscles: ['chest-upper'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Banc à 30-45°', 'Barre au niveau des clavicules', 'Poussez verticalement'] },
    { id: 'decline-bb-press', name: 'Développé Décliné Barre', targetMuscles: ['chest-lower'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Banc décliné, pieds calés', 'Descendez vers le bas du sternum', 'Poussez puissamment'] },
    { id: 'flat-db-press', name: 'Développé Couché Haltères', targetMuscles: ['chest-mid'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Allongé, haltères au dessus de la poitrine', 'Descendez en contrôle', 'Serrez en haut'] },
    { id: 'incline-db-press', name: 'Développé Incliné Haltères', targetMuscles: ['chest-upper'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Banc à 30-45°', 'Poussez vers le plafond', 'Contrôlez la descente'] },
    { id: 'decline-db-press', name: 'Développé Décliné Haltères', targetMuscles: ['chest-lower'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Banc décliné', 'Descendez en étirant les pecs', 'Contractez en haut'] },
    { id: 'db-fly', name: 'Écarté Couché Haltères', targetMuscles: ['chest-mid'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Bras tendus au-dessus', 'Ouvrez en arc de cercle', 'Serrez les pecs en haut'] },
    { id: 'incline-db-fly', name: 'Écarté Incliné Haltères', targetMuscles: ['chest-upper'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Banc incliné, bras ouverts', 'Ramenez en serrant le haut des pecs'] },
    { id: 'cable-crossover', name: 'Crossover Poulie Haute', targetMuscles: ['chest-lower'], equipment: ['cable'], difficulty: 'intermediate', category: 'strength', instructions: ['Poulies hautes, avancez le buste', 'Ramenez vers le nombril'] },
    { id: 'low-cable-fly', name: 'Écarté Poulie Basse', targetMuscles: ['chest-upper'], equipment: ['cable'], difficulty: 'intermediate', category: 'strength', instructions: ['Poulies basses', 'Ramenez vers le haut de la poitrine'] },
    { id: 'pushup-standard', name: 'Pompes Classiques', targetMuscles: ['chest-mid'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Mains largeur épaules', 'Corps gainé', 'Descendez au sol'] },
    { id: 'pushup-wide', name: 'Pompes Larges', targetMuscles: ['chest-mid'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Mains plus larges que les épaules', 'Ciblez les pecs'] },
    { id: 'pushup-diamond', name: 'Pompes Diamant', targetMuscles: ['triceps-long'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Mains en losange sous le sternum', 'Focus triceps'] },
    { id: 'pushup-decline', name: 'Pompes Pieds Surélevés', targetMuscles: ['chest-upper'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Pieds sur un banc', 'Ciblez le haut des pecs'] },
    { id: 'pushup-incline', name: 'Pompes Mains Surélevées', targetMuscles: ['chest-lower'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Mains sur un banc', 'Plus facile, bon pour débutants'] },
    { id: 'dips-chest', name: 'Dips Pectoraux', targetMuscles: ['chest-lower'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Buste penché en avant', 'Coudes vers l extérieur', 'Desc profonde'] },
    { id: 'machine-chest-press', name: 'Presse Pectorale Machine', targetMuscles: ['chest-mid'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Réglages à hauteur des pecs', 'Poussez horizontalement'] },
    { id: 'pec-deck', name: 'Pec Deck (Butterfly)', targetMuscles: ['chest-mid'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Avant-bras sur les coussinets', 'Serrez devant'] },
    { id: 'smith-bench-press', name: 'Dev Couché Smith Machine', targetMuscles: ['chest-mid'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Barre guidée, descendez au sternum'] },
    { id: 'landmine-press', name: 'Presse Landmine', targetMuscles: ['chest-upper'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Barre dans un coin, poussez en arc'] },
    { id: 'svend-press', name: 'Svend Press', targetMuscles: ['chest-mid'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Serrez deux poids devant vous, poussez'] },
    { id: 'floor-press', name: 'Floor Press', targetMuscles: ['chest-mid'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Au sol, amplitude réduite', 'Sécurisé pour les épaules'] },
    { id: 'close-grip-bench', name: 'Dev Couché Prise Serrée', targetMuscles: ['triceps-long', 'chest-mid'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Mains largeur épaules', 'Focus triceps et intérieur pecs'] },
];

// BACK EXERCISES (60+)
export const BACK_EXERCISES = [
    { id: 'pullup', name: 'Tractions Pronation', targetMuscles: ['lats'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Prise large', 'Tirez la poitrine vers la barre'] },
    { id: 'chinup', name: 'Tractions Supination', targetMuscles: ['lats', 'biceps-short'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Prise largeur épaules, paumes vers vous'] },
    { id: 'neutral-grip-pullup', name: 'Tractions Prise Neutre', targetMuscles: ['lats'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Paumes face à face, protège les épaules'] },
    { id: 'lat-pulldown', name: 'Tirage Vertical Poulie Haute', targetMuscles: ['lats'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Tirez vers la poitrine, pas derrière la nuque'] },
    { id: 'close-grip-pulldown', name: 'Tirage Prise Serrée', targetMuscles: ['lats'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Poignée triangle, tirez vers le sternum'] },
    { id: 'straight-arm-pulldown', name: 'Pullover Poulie Haute', targetMuscles: ['lats'], equipment: ['cable'], difficulty: 'intermediate', category: 'strength', instructions: ['Bras tendus, ramenez vers les cuisses'] },
    { id: 'bb-row', name: 'Rowing Barre', targetMuscles: ['lats', 'traps-mid-lower'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Buste penché, tirez au nombril'] },
    { id: 'db-row-1arm', name: 'Rowing Unilatéral Haltère', targetMuscles: ['lats'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Un genou sur le banc, tirez le coude vers le plafond'] },
    { id: 'db-row-2arm', name: 'Rowing Haltères Bilatéral', targetMuscles: ['lats'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Buste penché, tirez les deux haltères'] },
    { id: 'pendlay-row', name: 'Pendlay Row', targetMuscles: ['lats'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Barre au sol entre chaque rep, explosif'] },
    { id: 'tbar-row', name: 'T-Bar Row', targetMuscles: ['lats', 'traps-mid-lower'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Machine T-Bar ou landmine, tirez vers le torse'] },
    { id: 'cable-row-seated', name: 'Tirage Horizontal Poulie', targetMuscles: ['lats', 'traps-mid-lower'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Assis, tirez vers le nombril, serrez les omoplates'] },
    { id: 'chest-supported-row', name: 'Rowing Poitrine Supportée', targetMuscles: ['lats'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Allongé sur banc incliné, tirez les haltères'] },
    { id: 'meadows-row', name: 'Meadows Row', targetMuscles: ['lats'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Landmine, position perpendiculaire, tirez en arc'] },
    { id: 'inverted-row', name: 'Rowing Inversé (Australian)', targetMuscles: ['lats'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Sous une barre basse, tirez le corps vers la barre'] },
    { id: 'deadlift', name: 'Soulevé de Terre', targetMuscles: ['back', 'glutes-max', 'hamstrings'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Pieds largeur hanches, tirez en soulevant les hanches'] },
    { id: 'sumo-deadlift', name: 'Soulevé Sumo', targetMuscles: ['back', 'glutes-max'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Pieds larges, pointes vers l ext, buste plus droit'] },
    { id: 'romanian-deadlift', name: 'Soulevé Roumain', targetMuscles: ['hamstrings', 'glutes-max'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Jambes quasi tendues, descendez le long des cuisses'] },
    { id: 'db-rdl', name: 'RDL Haltères', targetMuscles: ['hamstrings'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Même mouvement, haltères le long des jambes'] },
    { id: 'rack-pull', name: 'Rack Pull', targetMuscles: ['back', 'traps-upper'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Barre sur supports, amplitude réduite, focus trapèzes'] },
    { id: 'hyperextension', name: 'Hyperextension', targetMuscles: ['back', 'glutes-max'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Hanches sur le support, montez le buste'] },
    { id: 'reverse-hyper', name: 'Reverse Hyperextension', targetMuscles: ['glutes-max', 'hamstrings'], equipment: ['machine'], difficulty: 'intermediate', category: 'strength', instructions: ['Buste fixe, levez les jambes'] },
    { id: 'face-pull', name: 'Face Pull', targetMuscles: ['delt-rear', 'traps-mid-lower'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Tirez vers le visage, écartez les mains'] },
    { id: 'band-pull-apart', name: 'Band Pull Apart', targetMuscles: ['delt-rear'], equipment: ['band'], difficulty: 'beginner', category: 'strength', instructions: ['Bande devant, écartez les bras'] },
    { id: 'seal-row', name: 'Seal Row', targetMuscles: ['lats'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Allongé sur banc élevé, tirez la barre vers le torse'] },
];

// LEGS EXERCISES (70+)
export const LEGS_EXERCISES = [
    { id: 'bb-squat', name: 'Squat Barre Arrière', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Barre sur les trapèzes', 'Descendez cuisses // au sol'] },
    { id: 'front-squat', name: 'Squat Avant', targetMuscles: ['quad-rectus'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Barre sur les deltoïdes avant', 'Buste très droit'] },
    { id: 'goblet-squat', name: 'Goblet Squat', targetMuscles: ['quad-rectus'], equipment: ['dumbbell', 'kettlebell'], difficulty: 'beginner', category: 'strength', instructions: ['Haltère/KB devant la poitrine', 'Descente profonde'] },
    { id: 'bulgarian-split', name: 'Bulgarian Split Squat', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Pied arrière sur un banc', 'Descendez le genou'] },
    { id: 'walking-lunges', name: 'Fentes Marchées', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Grand pas, genou au sol, alternez'] },
    { id: 'reverse-lunges', name: 'Fentes Arrière', targetMuscles: ['glutes-max'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Pas vers l arrière, genoux fléchis'] },
    { id: 'lateral-lunges', name: 'Fentes Latérales', targetMuscles: ['adductors'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Pas sur le côté, pliez une jambe'] },
    { id: 'step-ups', name: 'Step Ups', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Montez sur un banc/box, alternez'] },
    { id: 'leg-press', name: 'Presse à Cuisses', targetMuscles: ['quad-vastus'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Dos bien calé, descendez les genoux'] },
    { id: 'hack-squat', name: 'Hack Squat Machine', targetMuscles: ['quad-rectus'], equipment: ['machine'], difficulty: 'intermediate', category: 'strength', instructions: ['Dos collé au dossier, descendez profond'] },
    { id: 'leg-extension', name: 'Leg Extension', targetMuscles: ['quad-rectus'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Étendez les jambes, serrez les quads en haut'] },
    { id: 'leg-curl-lying', name: 'Leg Curl Couché', targetMuscles: ['hamstrings'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Allongé, ramenez les talons aux fesses'] },
    { id: 'leg-curl-seated', name: 'Leg Curl Assis', targetMuscles: ['hamstrings'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Assis, ramenez les talons sous vous'] },
    { id: 'leg-curl-standing', name: 'Leg Curl Debout', targetMuscles: ['hamstrings'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Une jambe à la fois, ramenez le talon'] },
    { id: 'nordic-curl', name: 'Nordic Curl', targetMuscles: ['hamstrings'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Genoux au sol, descendez le buste contrôlé'] },
    { id: 'hip-thrust', name: 'Hip Thrust', targetMuscles: ['glutes-max'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Dos sur un banc, barre sur les hanches, poussez'] },
    { id: 'glute-bridge', name: 'Glute Bridge', targetMuscles: ['glutes-max'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Au sol, poussez les hanches vers le plafond'] },
    { id: 'cable-pull-through', name: 'Pull Through Poulie', targetMuscles: ['glutes-max', 'hamstrings'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Poulie basse entre les jambes, poussez les hanches'] },
    { id: 'sumo-squat', name: 'Sumo Squat', targetMuscles: ['adductors'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Pieds très larges, pointes vers l ext'] },
    { id: 'adductor-machine', name: 'Machine Adducteurs', targetMuscles: ['adductors'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Serrez les cuisses l une vers l autre'] },
    { id: 'abductor-machine', name: 'Machine Abducteurs', targetMuscles: ['glutes-med'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Écartez les cuisses'] },
    { id: 'calf-raise-standing', name: 'Mollets Debout', targetMuscles: ['calves'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Montez sur la pointe des pieds'] },
    { id: 'calf-raise-seated', name: 'Mollets Assis', targetMuscles: ['calves'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Assis, genoux sous le coussin, montez'] },
    { id: 'calf-raise-donkey', name: 'Donkey Calf Raise', targetMuscles: ['calves'], equipment: ['machine'], difficulty: 'intermediate', category: 'strength', instructions: ['Penché, partenaire ou machine sur le dos'] },
    { id: 'sissy-squat', name: 'Sissy Squat', targetMuscles: ['quad-rectus'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Genoux en avant, buste en arrière, descendez'] },
    { id: 'pistol-squat', name: 'Pistol Squat', targetMuscles: ['quad-rectus'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Squat une jambe, l autre tendue devant'] },
    { id: 'box-squat', name: 'Box Squat', targetMuscles: ['quad-rectus', 'glutes-max'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Asseyez-vous sur un box, relevez-vous'] },
    { id: 'zercher-squat', name: 'Zercher Squat', targetMuscles: ['quad-rectus'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Barre dans le creux des coudes'] },
];

// SHOULDERS EXERCISES (40+)
export const SHOULDERS_EXERCISES = [
    { id: 'ohp', name: 'Développé Militaire', targetMuscles: ['delt-front'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Barre sur les clavicules, poussez au dessus de la tête'] },
    { id: 'db-ohp', name: 'Développé Haltères', targetMuscles: ['delt-front'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Haltères aux épaules, poussez vers le plafond'] },
    { id: 'arnold-press', name: 'Arnold Press', targetMuscles: ['delt-front', 'delt-side'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Rotation en poussant, mains devant -> côtés'] },
    { id: 'push-press', name: 'Push Press', targetMuscles: ['delt-front'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Petite impulsion des jambes, poussez'] },
    { id: 'lateral-raise', name: 'Élévations Latérales', targetMuscles: ['delt-side'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Levez les bras sur les côtés, légère flexion du coude'] },
    { id: 'cable-lateral-raise', name: 'Élévations Latérales Poulie', targetMuscles: ['delt-side'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Poulie basse, levez sur le côté'] },
    { id: 'machine-lateral-raise', name: 'Machine Élévations Latérales', targetMuscles: ['delt-side'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Poussez les coussinets vers l ext'] },
    { id: 'front-raise', name: 'Élévations Frontales', targetMuscles: ['delt-front'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Levez les bras devant vous'] },
    { id: 'cable-front-raise', name: 'Élévations Frontales Poulie', targetMuscles: ['delt-front'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Poulie basse devant, levez'] },
    { id: 'bent-over-rear-fly', name: 'Oiseau (Rear Delt Fly)', targetMuscles: ['delt-rear'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Penché, écartez les bras'] },
    { id: 'cable-rear-fly', name: 'Écarté Arrière Poulie', targetMuscles: ['delt-rear'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Poulies hautes croisées, tirez vers l ext'] },
    { id: 'reverse-pec-deck', name: 'Pec Deck Inversé', targetMuscles: ['delt-rear'], equipment: ['machine'], difficulty: 'beginner', category: 'strength', instructions: ['Face à la machine, tirez les poignées en arrière'] },
    { id: 'upright-row', name: 'Rowing Menton', targetMuscles: ['delt-side', 'traps-upper'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Tirez la barre vers le menton, coudes hauts'] },
    { id: 'shrugs-bb', name: 'Shrugs Barre', targetMuscles: ['traps-upper'], equipment: ['barbell'], difficulty: 'beginner', category: 'strength', instructions: ['Haussez les épaules, tenez en haut'] },
    { id: 'shrugs-db', name: 'Shrugs Haltères', targetMuscles: ['traps-upper'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Idem avec haltères le long du corps'] },
    { id: 'lu-raise', name: 'Lu Raise', targetMuscles: ['delt-front', 'delt-side'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Thumb up, levez jusqu à 45°'] },
    { id: 'landmine-press-shoulder', name: 'Landmine Press Épaule', targetMuscles: ['delt-front'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Poussez la barre à un angle'] },
    { id: 'z-press', name: 'Z Press', targetMuscles: ['delt-front'], equipment: ['barbell'], difficulty: 'advanced', category: 'strength', instructions: ['Assis au sol, jambes tendues, poussez'] },
    { id: 'db-y-raise', name: 'Y Raise', targetMuscles: ['traps-mid-lower'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Buste penché, levez en Y'] },
    { id: 'face-pull-rope', name: 'Face Pull Corde', targetMuscles: ['delt-rear', 'rotator-cuff'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Tirez vers le visage, rotation externe'] },
];

// ARMS EXERCISES (50+)
export const ARMS_EXERCISES = [
    // BICEPS
    { id: 'bb-curl', name: 'Curl Barre', targetMuscles: ['biceps-short', 'biceps-long'], equipment: ['barbell'], difficulty: 'beginner', category: 'strength', instructions: ['Bras tendus, montez vers les épaules'] },
    { id: 'ez-curl', name: 'Curl Barre EZ', targetMuscles: ['biceps-short'], equipment: ['barbell'], difficulty: 'beginner', category: 'strength', instructions: ['Prise EZ, plus doux pour les poignets'] },
    { id: 'db-curl', name: 'Curl Haltères', targetMuscles: ['biceps-short'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Alternez ou simultané, supination'] },
    { id: 'hammer-curl', name: 'Curl Marteau', targetMuscles: ['biceps-long', 'forearms'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Paumes face à face, montez'] },
    { id: 'incline-curl', name: 'Curl Incliné', targetMuscles: ['biceps-long'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Sur banc incliné, bras pendants, curl'] },
    { id: 'preacher-curl', name: 'Curl Pupitre', targetMuscles: ['biceps-short'], equipment: ['barbell'], difficulty: 'beginner', category: 'strength', instructions: ['Bras sur le pupitre, curl sans tricher'] },
    { id: 'concentration-curl', name: 'Curl Concentration', targetMuscles: ['biceps-short'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Coude sur la cuisse, curl strict'] },
    { id: 'cable-curl', name: 'Curl Poulie Basse', targetMuscles: ['biceps-short'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Curl avec câble, tension constante'] },
    { id: 'drag-curl', name: 'Drag Curl', targetMuscles: ['biceps-long'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Tirez la barre le long du corps'] },
    { id: 'spider-curl', name: 'Spider Curl', targetMuscles: ['biceps-short'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Allongé sur banc incliné face vers le bas'] },
    { id: 'cross-body-curl', name: 'Curl Cross Body', targetMuscles: ['biceps-long'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Curl vers l épaule opposée'] },
    { id: 'reverse-curl', name: 'Curl Pronation', targetMuscles: ['forearms'], equipment: ['barbell'], difficulty: 'beginner', category: 'strength', instructions: ['Paume vers le bas, curl'] },
    { id: 'zottman-curl', name: 'Zottman Curl', targetMuscles: ['biceps-short', 'forearms'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Montée supination, descente pronation'] },
    // TRICEPS
    { id: 'triceps-pushdown', name: 'Extension Triceps Poulie', targetMuscles: ['triceps-lateral'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Poussez vers le bas, coudes fixes'] },
    { id: 'rope-pushdown', name: 'Extension Triceps Corde', targetMuscles: ['triceps-lateral'], equipment: ['cable'], difficulty: 'beginner', category: 'strength', instructions: ['Écartez la corde en bas'] },
    { id: 'overhead-cable-ext', name: 'Extension Overhead Poulie', targetMuscles: ['triceps-long'], equipment: ['cable'], difficulty: 'intermediate', category: 'strength', instructions: ['Bras au dessus de la tête, étendez'] },
    { id: 'skull-crusher', name: 'Skull Crusher', targetMuscles: ['triceps-long'], equipment: ['barbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Allongé, descendez vers le front'] },
    { id: 'db-skull-crusher', name: 'Skull Crusher Haltères', targetMuscles: ['triceps-long'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Idem avec haltères'] },
    { id: 'overhead-db-ext', name: 'Extension Haltère au dessus', targetMuscles: ['triceps-long'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Haltère à deux mains, descendez derrière la tête'] },
    { id: 'kickback', name: 'Kickback Triceps', targetMuscles: ['triceps-lateral'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Penché, étendez le bras vers l arrière'] },
    { id: 'dips-triceps', name: 'Dips Triceps', targetMuscles: ['triceps-long'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Buste droit, coudes serrés'] },
    { id: 'bench-dips', name: 'Dips sur Banc', targetMuscles: ['triceps-long'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Mains sur banc derrière, descendez'] },
    { id: 'close-grip-pushup', name: 'Pompes Serrées', targetMuscles: ['triceps-long'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Mains sous les épaules, coudes au corps'] },
    // FOREARMS
    { id: 'wrist-curl', name: 'Curl Poignet', targetMuscles: ['forearms'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Avant-bras sur cuisse, curl du poignet'] },
    { id: 'reverse-wrist-curl', name: 'Curl Poignet Inversé', targetMuscles: ['forearms'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Idem paume vers le bas'] },
    { id: 'farmers-walk', name: 'Farmer Walk', targetMuscles: ['forearms', 'traps-upper'], equipment: ['dumbbell'], difficulty: 'beginner', category: 'strength', instructions: ['Marchez avec poids lourds'] },
    { id: 'plate-pinch', name: 'Plate Pinch', targetMuscles: ['forearms'], equipment: ['dumbbell'], difficulty: 'intermediate', category: 'strength', instructions: ['Pincez deux disques ensemble'] },
];

// CORE/ABS EXERCISES (40+)
export const CORE_EXERCISES = [
    { id: 'plank', name: 'Planche', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Maintenez la position, corps gainé'] },
    { id: 'crunch', name: 'Crunch', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Décollez les épaules, contractez les abdos'] },
    { id: 'sit-up', name: 'Sit Up', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Remontez complètement le buste'] },
    { id: 'leg-raise', name: 'Relevé de Jambes', targetMuscles: ['abs-lower'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Jambes tendues, montez à 90°'] },
    { id: 'hanging-leg-raise', name: 'Relevé de Jambes Suspendu', targetMuscles: ['abs-lower'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Suspendu à une barre, montez les jambes'] },
    { id: 'knee-raise', name: 'Relevé de Genoux', targetMuscles: ['abs-lower'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Variante plus facile, genoux pliés'] },
    { id: 'russian-twist', name: 'Russian Twist', targetMuscles: ['obliques'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Assis, rotation du buste gauche/droite'] },
    { id: 'bicycle-crunch', name: 'Crunch Bicyclette', targetMuscles: ['obliques', 'abs-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Coude vers genou opposé, alternez'] },
    { id: 'mountain-climber', name: 'Mountain Climbers', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'cardio', instructions: ['Position pompe, genoux vers la poitrine alternés'] },
    { id: 'dead-bug', name: 'Dead Bug', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Sur le dos, étendez bras et jambes opposés'] },
    { id: 'bird-dog', name: 'Bird Dog', targetMuscles: ['back', 'abs-rectus'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['À quatre pattes, étendez bras et jambe opposés'] },
    { id: 'ab-wheel', name: 'Ab Wheel Rollout', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Roulez vers l avant, revenez'] },
    { id: 'cable-crunch', name: 'Crunch Poulie Haute', targetMuscles: ['abs-rectus'], equipment: ['cable'], difficulty: 'intermediate', category: 'strength', instructions: ['À genoux, tirez la corde vers le sol'] },
    { id: 'pallof-press', name: 'Pallof Press', targetMuscles: ['obliques'], equipment: ['cable'], difficulty: 'intermediate', category: 'strength', instructions: ['Poulie latérale, poussez devant, résistez à la rotation'] },
    { id: 'side-plank', name: 'Planche Latérale', targetMuscles: ['obliques'], equipment: ['bodyweight'], difficulty: 'beginner', category: 'strength', instructions: ['Sur le côté, hanches hautes'] },
    { id: 'hollow-hold', name: 'Hollow Hold', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Dos au sol, jambes et épaules décollées'] },
    { id: 'dragon-flag', name: 'Dragon Flag', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Allongé, levez le corps en un bloc'] },
    { id: 'toes-to-bar', name: 'Toes to Bar', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Suspendu, amenez les pieds à la barre'] },
    { id: 'l-sit', name: 'L-Sit', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'advanced', category: 'strength', instructions: ['Corps en L, bras tendus'] },
    { id: 'v-up', name: 'V-Up', targetMuscles: ['abs-rectus'], equipment: ['bodyweight'], difficulty: 'intermediate', category: 'strength', instructions: ['Montez bras et jambes simultanément'] },
];
